#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp_68PM2_TranQuangTien_0025968
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLSV")]
	public partial class databaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdiem(diem instance);
    partial void Updatediem(diem instance);
    partial void Deletediem(diem instance);
    partial void Insertlophoc(lophoc instance);
    partial void Updatelophoc(lophoc instance);
    partial void Deletelophoc(lophoc instance);
    partial void Insertmonhoc(monhoc instance);
    partial void Updatemonhoc(monhoc instance);
    partial void Deletemonhoc(monhoc instance);
    partial void Insertsinhvien(sinhvien instance);
    partial void Updatesinhvien(sinhvien instance);
    partial void Deletesinhvien(sinhvien instance);
    #endregion
		
		public databaseDataContext() : 
				base(global::CSharp_68PM2_TranQuangTien_0025968.Properties.Settings.Default.QLSVConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<diem> diems
		{
			get
			{
				return this.GetTable<diem>();
			}
		}
		
		public System.Data.Linq.Table<lophoc> lophocs
		{
			get
			{
				return this.GetTable<lophoc>();
			}
		}
		
		public System.Data.Linq.Table<monhoc> monhocs
		{
			get
			{
				return this.GetTable<monhoc>();
			}
		}
		
		public System.Data.Linq.Table<sinhvien> sinhviens
		{
			get
			{
				return this.GetTable<sinhvien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.diem")]
	public partial class diem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _madiem;
		
		private string _masv;
		
		private string _mamh;
		
		private System.Nullable<double> _diemlan1;
		
		private System.Nullable<double> _diemlan2;
		
		private EntityRef<monhoc> _monhoc;
		
		private EntityRef<sinhvien> _sinhvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadiemChanging(int value);
    partial void OnmadiemChanged();
    partial void OnmasvChanging(string value);
    partial void OnmasvChanged();
    partial void OnmamhChanging(string value);
    partial void OnmamhChanged();
    partial void Ondiemlan1Changing(System.Nullable<double> value);
    partial void Ondiemlan1Changed();
    partial void Ondiemlan2Changing(System.Nullable<double> value);
    partial void Ondiemlan2Changed();
    #endregion
		
		public diem()
		{
			this._monhoc = default(EntityRef<monhoc>);
			this._sinhvien = default(EntityRef<sinhvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madiem", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int madiem
		{
			get
			{
				return this._madiem;
			}
			set
			{
				if ((this._madiem != value))
				{
					this.OnmadiemChanging(value);
					this.SendPropertyChanging();
					this._madiem = value;
					this.SendPropertyChanged("madiem");
					this.OnmadiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masv", DbType="VarChar(10)")]
		public string masv
		{
			get
			{
				return this._masv;
			}
			set
			{
				if ((this._masv != value))
				{
					if (this._sinhvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmasvChanging(value);
					this.SendPropertyChanging();
					this._masv = value;
					this.SendPropertyChanged("masv");
					this.OnmasvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mamh", DbType="VarChar(10)")]
		public string mamh
		{
			get
			{
				return this._mamh;
			}
			set
			{
				if ((this._mamh != value))
				{
					if (this._monhoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmamhChanging(value);
					this.SendPropertyChanging();
					this._mamh = value;
					this.SendPropertyChanged("mamh");
					this.OnmamhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemlan1", DbType="Float")]
		public System.Nullable<double> diemlan1
		{
			get
			{
				return this._diemlan1;
			}
			set
			{
				if ((this._diemlan1 != value))
				{
					this.Ondiemlan1Changing(value);
					this.SendPropertyChanging();
					this._diemlan1 = value;
					this.SendPropertyChanged("diemlan1");
					this.Ondiemlan1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diemlan2", DbType="Float")]
		public System.Nullable<double> diemlan2
		{
			get
			{
				return this._diemlan2;
			}
			set
			{
				if ((this._diemlan2 != value))
				{
					this.Ondiemlan2Changing(value);
					this.SendPropertyChanging();
					this._diemlan2 = value;
					this.SendPropertyChanged("diemlan2");
					this.Ondiemlan2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="monhoc_diem", Storage="_monhoc", ThisKey="mamh", OtherKey="mamh", IsForeignKey=true)]
		public monhoc monhoc
		{
			get
			{
				return this._monhoc.Entity;
			}
			set
			{
				monhoc previousValue = this._monhoc.Entity;
				if (((previousValue != value) 
							|| (this._monhoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._monhoc.Entity = null;
						previousValue.diems.Remove(this);
					}
					this._monhoc.Entity = value;
					if ((value != null))
					{
						value.diems.Add(this);
						this._mamh = value.mamh;
					}
					else
					{
						this._mamh = default(string);
					}
					this.SendPropertyChanged("monhoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sinhvien_diem", Storage="_sinhvien", ThisKey="masv", OtherKey="masv", IsForeignKey=true)]
		public sinhvien sinhvien
		{
			get
			{
				return this._sinhvien.Entity;
			}
			set
			{
				sinhvien previousValue = this._sinhvien.Entity;
				if (((previousValue != value) 
							|| (this._sinhvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sinhvien.Entity = null;
						previousValue.diems.Remove(this);
					}
					this._sinhvien.Entity = value;
					if ((value != null))
					{
						value.diems.Add(this);
						this._masv = value.masv;
					}
					else
					{
						this._masv = default(string);
					}
					this.SendPropertyChanged("sinhvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lophoc")]
	public partial class lophoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _malop;
		
		private string _tenlop;
		
		private string _khoahoc;
		
		private System.Nullable<int> _namhoc;
		
		private EntitySet<sinhvien> _sinhviens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmalopChanging(string value);
    partial void OnmalopChanged();
    partial void OntenlopChanging(string value);
    partial void OntenlopChanged();
    partial void OnkhoahocChanging(string value);
    partial void OnkhoahocChanged();
    partial void OnnamhocChanging(System.Nullable<int> value);
    partial void OnnamhocChanged();
    #endregion
		
		public lophoc()
		{
			this._sinhviens = new EntitySet<sinhvien>(new Action<sinhvien>(this.attach_sinhviens), new Action<sinhvien>(this.detach_sinhviens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_malop", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string malop
		{
			get
			{
				return this._malop;
			}
			set
			{
				if ((this._malop != value))
				{
					this.OnmalopChanging(value);
					this.SendPropertyChanging();
					this._malop = value;
					this.SendPropertyChanged("malop");
					this.OnmalopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenlop", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenlop
		{
			get
			{
				return this._tenlop;
			}
			set
			{
				if ((this._tenlop != value))
				{
					this.OntenlopChanging(value);
					this.SendPropertyChanging();
					this._tenlop = value;
					this.SendPropertyChanged("tenlop");
					this.OntenlopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoahoc", DbType="NVarChar(50)")]
		public string khoahoc
		{
			get
			{
				return this._khoahoc;
			}
			set
			{
				if ((this._khoahoc != value))
				{
					this.OnkhoahocChanging(value);
					this.SendPropertyChanging();
					this._khoahoc = value;
					this.SendPropertyChanged("khoahoc");
					this.OnkhoahocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namhoc", DbType="Int")]
		public System.Nullable<int> namhoc
		{
			get
			{
				return this._namhoc;
			}
			set
			{
				if ((this._namhoc != value))
				{
					this.OnnamhocChanging(value);
					this.SendPropertyChanging();
					this._namhoc = value;
					this.SendPropertyChanged("namhoc");
					this.OnnamhocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lophoc_sinhvien", Storage="_sinhviens", ThisKey="malop", OtherKey="malop")]
		public EntitySet<sinhvien> sinhviens
		{
			get
			{
				return this._sinhviens;
			}
			set
			{
				this._sinhviens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sinhviens(sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.lophoc = this;
		}
		
		private void detach_sinhviens(sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.lophoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.monhoc")]
	public partial class monhoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mamh;
		
		private string _tenmh;
		
		private int _sotinchi;
		
		private EntitySet<diem> _diems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmamhChanging(string value);
    partial void OnmamhChanged();
    partial void OntenmhChanging(string value);
    partial void OntenmhChanged();
    partial void OnsotinchiChanging(int value);
    partial void OnsotinchiChanged();
    #endregion
		
		public monhoc()
		{
			this._diems = new EntitySet<diem>(new Action<diem>(this.attach_diems), new Action<diem>(this.detach_diems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mamh", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mamh
		{
			get
			{
				return this._mamh;
			}
			set
			{
				if ((this._mamh != value))
				{
					this.OnmamhChanging(value);
					this.SendPropertyChanging();
					this._mamh = value;
					this.SendPropertyChanged("mamh");
					this.OnmamhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenmh", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenmh
		{
			get
			{
				return this._tenmh;
			}
			set
			{
				if ((this._tenmh != value))
				{
					this.OntenmhChanging(value);
					this.SendPropertyChanging();
					this._tenmh = value;
					this.SendPropertyChanged("tenmh");
					this.OntenmhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sotinchi", DbType="Int NOT NULL")]
		public int sotinchi
		{
			get
			{
				return this._sotinchi;
			}
			set
			{
				if ((this._sotinchi != value))
				{
					this.OnsotinchiChanging(value);
					this.SendPropertyChanging();
					this._sotinchi = value;
					this.SendPropertyChanged("sotinchi");
					this.OnsotinchiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="monhoc_diem", Storage="_diems", ThisKey="mamh", OtherKey="mamh")]
		public EntitySet<diem> diems
		{
			get
			{
				return this._diems;
			}
			set
			{
				this._diems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_diems(diem entity)
		{
			this.SendPropertyChanging();
			entity.monhoc = this;
		}
		
		private void detach_diems(diem entity)
		{
			this.SendPropertyChanging();
			entity.monhoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sinhvien")]
	public partial class sinhvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _masv;
		
		private string _hoten;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private string _gioitinh;
		
		private string _diachi;
		
		private string _sdt;
		
		private string _email;
		
		private string _malop;
		
		private EntitySet<diem> _diems;
		
		private EntityRef<lophoc> _lophoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmasvChanging(string value);
    partial void OnmasvChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnmalopChanging(string value);
    partial void OnmalopChanged();
    #endregion
		
		public sinhvien()
		{
			this._diems = new EntitySet<diem>(new Action<diem>(this.attach_diems), new Action<diem>(this.detach_diems));
			this._lophoc = default(EntityRef<lophoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masv", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string masv
		{
			get
			{
				return this._masv;
			}
			set
			{
				if ((this._masv != value))
				{
					this.OnmasvChanging(value);
					this.SendPropertyChanging();
					this._masv = value;
					this.SendPropertyChanged("masv");
					this.OnmasvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(10)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(200)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(15)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_malop", DbType="VarChar(10)")]
		public string malop
		{
			get
			{
				return this._malop;
			}
			set
			{
				if ((this._malop != value))
				{
					if (this._lophoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmalopChanging(value);
					this.SendPropertyChanging();
					this._malop = value;
					this.SendPropertyChanged("malop");
					this.OnmalopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sinhvien_diem", Storage="_diems", ThisKey="masv", OtherKey="masv")]
		public EntitySet<diem> diems
		{
			get
			{
				return this._diems;
			}
			set
			{
				this._diems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lophoc_sinhvien", Storage="_lophoc", ThisKey="malop", OtherKey="malop", IsForeignKey=true)]
		public lophoc lophoc
		{
			get
			{
				return this._lophoc.Entity;
			}
			set
			{
				lophoc previousValue = this._lophoc.Entity;
				if (((previousValue != value) 
							|| (this._lophoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._lophoc.Entity = null;
						previousValue.sinhviens.Remove(this);
					}
					this._lophoc.Entity = value;
					if ((value != null))
					{
						value.sinhviens.Add(this);
						this._malop = value.malop;
					}
					else
					{
						this._malop = default(string);
					}
					this.SendPropertyChanged("lophoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_diems(diem entity)
		{
			this.SendPropertyChanging();
			entity.sinhvien = this;
		}
		
		private void detach_diems(diem entity)
		{
			this.SendPropertyChanging();
			entity.sinhvien = null;
		}
	}
}
#pragma warning restore 1591
